# Generated by Django 2.0.8 on 2018-08-20 08:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import pgcrypto.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, validators=[django.core.validators.RegexValidator(message='存在非法字符', regex='^[a-zA-Z0-9_\\.\\-]+$')])),
            ],
            options={
                'ordering': ['name'],
                'permissions': (('viwe_application', 'Can view application'), ('execute_aaplication', 'Can execute application')),
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, validators=[django.core.validators.RegexValidator(message='存在非法字符', regex='^[a-zA-Z0-9_\\.\\-]+$')])),
            ],
            options={
                'ordering': ['name'],
                'permissions': (('view_department', 'Can view department'), ('execute_department', 'Can execute department')),
            },
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, validators=[django.core.validators.RegexValidator(message='存在非法字符', regex='^[a-zA-Z0-9_\\.\\-]+$')])),
                ('is_production', models.BooleanField(default=False)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environments', to='proverty.Application')),
            ],
            options={
                'ordering': ['name'],
                'permissions': (('view_environment', 'Can view environment'), ('execute_environment', 'Can execute environment')),
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, validators=[django.core.validators.RegexValidator(message='存在非法字符', regex='^[a-zA-Z0-9_\\.\\-]+$')])),
                ('host', models.CharField(max_length=128)),
                ('port', models.IntegerField()),
                ('method', models.IntegerField(choices=[(2, 'SSH certificate'), (1, 'SSH password')], default=2, verbose_name='Login method')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServerRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, validators=[django.core.validators.RegexValidator(message='存在非法字符', regex='^[a-zA-Z0-9_\\.\\-]+$')])),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serverroles', to='proverty.Department')),
            ],
        ),
        migrations.CreateModel(
            name='ServerAuthentication',
            fields=[
                ('server', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='proverty.Server')),
                ('password', pgcrypto.fields.EncryptedTextField(blank=True, charset='utf-8', check_armor=True, cipher='AES', versioned=False)),
            ],
        ),
        migrations.AddField(
            model_name='server',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servers', to='proverty.Environment'),
        ),
        migrations.AddField(
            model_name='server',
            name='roles',
            field=models.ManyToManyField(related_name='servers', to='proverty.ServerRole'),
        ),
        migrations.AddField(
            model_name='application',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='proverty.Department'),
        ),
        migrations.AlterUniqueTogether(
            name='serverrole',
            unique_together={('department', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='server',
            unique_together={('environment', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='environment',
            unique_together={('application', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('department', 'name')},
        ),
    ]
